# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricIndexes',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='Id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
                ('nasqad', models.DecimalField(db_column='Nasdaq', decimal_places=19, max_digits=20)),
                ('dowjones', models.DecimalField(db_column='Dowjones', decimal_places=19, max_digits=20)),
                ('snp500', models.DecimalField(db_column='SnP500', decimal_places=19, max_digits=20)),
                ('rates', models.DecimalField(db_column='Rates', decimal_places=19, max_digits=20)),
            ],
            options={
                'db_table': 'HistoricIndexes',
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
